name: mein
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  cupertino_icons: ^0.1.3
  gcloud: ^0.7.3
  googleapis_auth: ^0.2.12
  mime: ^0.9.7
  permission_handler: ^3.2.0
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  firebase_analytics: ^5.0.2
  image_picker: ^0.6.7+22
  flutter:
    sdk: flutter
  camera:
  path_provider:
  path:
  google_maps_flutter:
  flutter_mobile_vision: ^0.1.4+1
  #edge_detection: ^1.0.6


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  rating_dialog: ^2.0.1
  dio: ^3.0.10
  #file_picker: ^3.0.3
  vertical_barchart: ^2.0.0
  http: ^0.12.2
  get: ^4.3.8
  #cloud_firestore: ^0.13.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/credentials.json
    - images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
#
#  fonts:
#    - family: Sans
#      fonts:
#        - asset: font/PTSans-Bold.ttf
#          weight: 700
#        - asset: font/PTSans-Regular.ttf
#          weight: 400

    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
